Ios build
numbersprotocol/capture-lite pull request #108
Opened 2020-09-21 05:56 UTC by CS6

增加 ios 環境與設定

2020-09-21 05:59 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 16
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975&bid=20249226)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
Codacy found an issue: [Line should be 120 characters or less: currently 151 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Limit vertical whitespace to a single empty line. Currently 2.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is te
Codacy found an issue: [Line should be 120 characters or less: currently 214 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 05:59 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6208975)

2020-09-21 06:16 UTC, CS6 commented
@bafu   PR Quality Review 對於 Ionic 自動建立的 ios swift 的 issue 需要處理嗎？

2020-09-21 06:56 UTC, seanwu1105 commented
> @bafu PR Quality Review 對於 Ionic 自動建立的 ios swift 的 issue 需要處理嗎？

@CS6 這個 Quality Review 是我建立的，不過我沒有針對 Swift 做 linting 的設定，你可以簡單參考或是直接進 Codacy 修改 linting 規定即可。

2020-09-22 02:50 UTC, shc261392 requested changes

2020-09-22 02:50 UTC, shc261392 commented on package.json
> +    "@capacitor/ios": "^2.4.0",
@capacitor/ios should be bumped to 2.4.1 as well

2020-09-22 04:05 UTC, shc261392 approved these changes

2020-09-22 04:05 UTC, merged