Feature category
numbersprotocol/capture-lite pull request #109
Opened 2020-09-21 06:02 UTC by CS6

issue #95 https://github.com/numbersprotocol/capture-lite/issues/95
Categorize photos by creation date #95

按照日期分組照片

![image](https://user-images.githubusercontent.com/16307922/93736307-7e7db580-fc12-11ea-9dc3-dc4b0334c7ac.png)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +padding-top: 10px;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +margin-left: 5vw;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +padding-bottom: 10px;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +.Title {
Codacy found an issue: [Expected empty line before rule (rule-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +text-align: start;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
Codacy found an issue: [Line should be 120 characters or less: currently 151 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +.setTitle {
Codacy found an issue: [Expected empty line before rule (rule-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +color: #000;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: calc(90vw/3);
Codacy found an issue: [Expected single space before "/" operator (function-calc-no-unspaced-operator)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:04 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:20 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Limit vertical whitespace to a single empty line. Currently 2.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is te
Codacy found an issue: [Line should be 120 characters or less: currently 214 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: calc(90vw/3);
Codacy found an issue: [Expected single space before "/" operator (function-calc-no-unspaced-operator)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
Codacy found an issue: [Line should be 120 characters or less: currently 151 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:21 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 06:25 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  margin: calc( var( --ion-padding, 9px ) / 3 );
Codacy found an issue: [Unexpected whitespace after "(" in a single-line function (function-parentheses-space-inside)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is te
Codacy found an issue: [Line should be 120 characters or less: currently 214 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Limit vertical whitespace to a single empty line. Currently 2.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: calc( 90vw / 3 );
Codacy found an issue: [Unexpected whitespace after "(" in a single-line function (function-parentheses-space-inside)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
Codacy found an issue: [Line should be 120 characters or less: currently 151 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:25 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 06:26 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 08:26 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 08:26 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 08:31 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 09:13 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 09:13 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Unexpected whitespace at end of line (no-eol-whitespace)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 09:28 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 09:28 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Unexpected whitespace at end of line (no-eol-whitespace)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 09:36 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 09:36 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: 90vw;
Codacy found an issue: [Unexpected whitespace at end of line (no-eol-whitespace)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 09:36 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: 90vw;
Codacy found an issue: [Expected newline after ";" in a multi-line declaration block (declaration-block-semicolon-newline-after)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 09:36 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 09:44 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Coverage decreased per file
===========================
- src/app/pages/storage/storage.page.ts  -29
- src/app/services/collector/signature/default-provider/default-provider.ts  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-21 09:44 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Unexpected whitespace at end of line (no-eol-whitespace)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007)

2020-09-21 09:49 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- src/app/pages/storage/storage.page.ts  -29
- src/app/services/collector/signature/default-provider/default-provider.ts  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-22 04:23 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/app/utils/storage/storage.ts  8
         

Coverage decreased per file
===========================
- src/app/pages/storage/storage.page.ts  -23
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209007&bid=20249283)

2020-09-22 07:56 UTC, shc261392 requested changes

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +  readonly today$ = new Observable(observer => {
This observable emits `''` after 1000 ms. I don't think it's relevant to "today" and it looks unnecessary here.

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +              date === '' ||
`date` is always `''` so there's no point in comparing `date === ''`

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +  getDays(date: any) {
推薦用比較 Angular 的方式 format date

ex.

```
import { formatDate } from '@angular/common';

getDate(timestamp: number) {
    return formatDate(timestamp, 'mediumDate', 'en-US');
}
```

return 會是 `Sep 22, 2020`

其他 formatting 方式可以參考 https://angular.io/api/common/DatePipe

另外建議除非沒有其他選擇否則不要用 `any` ，不然就失去使用型別的意義了

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +  readonly proofsWithRawByDate$ = this.proofs$.pipe(
已經有 `proofsWithRaw$` 存在不需要從 `proof$` 重新開始做一次一樣的事

```
readonly proofsWithRawByDate$ = this.proofsWithRaw$.pipe(
    map(proofsWithRaw => proofsWithRaw.sort((a, b) => a.proof.timestamp - b.proof.timestamp),
    mergeMap(...),
    ...
);
```

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +                new Date(processingproofsWithRawBase64[0].proof.timestamp)
date format 方式建議參考下方 getDays 包一下

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +    // tap(console.log)
commented codes should be deleted

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.html
> +        <!-- {{ proofWithSet[0].proof.timestamp}} -->
commented codes should be deleted

2020-09-22 07:56 UTC, shc261392 commented on src/app/pages/storage/storage.page.html
> +          <!-- <h1>{{ proofWithRaw.proof.timestamp}}</h1> -->
commented codes should be deleted

2020-09-22 19:15 UTC, CS6 commented
@shc261392  以解決上述問題，且通過CI檢查

2020-09-23 03:44 UTC, shc261392 requested changes

2020-09-23 03:44 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +    observer.next('');
我還是不知道 `today$` 的功用是什麼？它只會立刻 emit `''`

2020-09-23 03:44 UTC, shc261392 commented on src/app/pages/storage/storage.page.html
> +      <div class="setTitle"><strong>{{getDate(proofWithSet[0].proof.timestamp)}}</strong></div>
在 template 裡面使用 function call 的一個問題是，每當整個 component 的 change detection 被觸發的時候就會重新呼叫一次 function ，如果你打開 console 就會看到這個 function 在 component initiate 時不斷被重複呼叫

原則上除非有好理由，否則盡量避免在 template 中使用 function call

可以參考 https://medium.com/showpad-engineering/why-you-should-never-use-function-calls-in-angular-template-expressions-e1a50f9c0496

這裏比較好的方式是在 `proofsWithRawByDate$` 剛接到 `proofsWithRaw$` 的結果時做一次資料的變換，直接把 date 加進去（增加 date 這個 object property ），因為 date 是跟著 timestamp 的，原本的 timestamp 不變就不會改變，不需要在最後顯示的時候才轉換，這也是我一開始的 suggested implementation

```
...
map(proofsWithRaw => proofsWithRaw.map(proofWithRaw => ({ ...proofWithRaw, date: this.getDate(proofWithRaw.proof.timestamp) }))),
...
```

然後在 template

```
<div class="setTitle"><strong>{{ proofWithSet[0].date }}</strong></div>
```

就可以避免上述情況發生

2020-09-23 03:44 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +              true ||
這裡不清楚為什麼要 `true ||` 還有將 date 跟 `''` 比較，這個 filter 因為恆真應該沒有功能

2020-09-23 03:44 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +                this.getDate(processingproofsWithRawBase64[0].proof.timestamp)
如果按前面說的先存下 date 的話這裡可以直接 `processingproofsWithRawBase64[0].date === proofWithRawBase64.date`

2020-09-23 03:44 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +    console.log(formatDate(timestamp, 'mediumDate', 'en-US'));
這個在最後推上來的版本還是要記得刪掉，因為資料多的時候會洗版 console log ，而且如果這個功能做好之後不需要一直看這個 log

2020-09-23 03:49 UTC, CS6 commented on src/app/pages/storage/storage.page.ts
> +    console.log(formatDate(timestamp, 'mediumDate', 'en-US'));
抱歉我忽略了ＱＱ

2020-09-23 06:38 UTC, shc261392 approved these changes

2020-09-23 06:39 UTC, merged