Feature topbar ui
numbersprotocol/capture-lite pull request #110
Opened 2020-09-21 06:06 UTC by CS6

調整 Top Tab Bar 符合 UI style 以及在小螢幕裝置上的可用性 

![image](https://user-images.githubusercontent.com/16307922/93736630-868a2500-fc13-11ea-98bf-4a6fb042ef07.png)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +padding-top: 10px;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +color: #000;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: calc(90vw/3);
Codacy found an issue: [Expected single space before "/" operator (function-calc-no-unspaced-operator)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is te
Codacy found an issue: [Line should be 120 characters or less: currently 214 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +padding-bottom: 10px;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +margin-left: 5vw;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Limit vertical whitespace to a single empty line. Currently 2.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +text-align: start;
Codacy found an issue: [Expected indentation of 2 spaces (indentation)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +.setTitle {
Codacy found an issue: [Expected empty line before rule (rule-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:08 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:09 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:09 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +.Title {
Codacy found an issue: [Expected empty line before rule (rule-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:09 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:09 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:09 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:09 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:15 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-21 06:15 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:15 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:15 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Limit vertical whitespace to a single empty line. Currently 2.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:15 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:15 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: calc(90vw/3);
Codacy found an issue: [Expected single space before "/" operator (function-calc-no-unspaced-operator)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
Codacy found an issue: [Line should be 120 characters or less: currently 151 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:16 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is te
Codacy found an issue: [Line should be 120 characters or less: currently 214 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:27 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
Codacy found an issue: [Line should be 120 characters or less: currently 190 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Files should have a single trailing newline.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
Codacy found an issue: [Line should be 120 characters or less: currently 124 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when th
Codacy found an issue: [Line should be 120 characters or less: currently 281 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
Codacy found an issue: [Line should be 120 characters or less: currently 151 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Limit vertical whitespace to a single empty line. Currently 2.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 165 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
Codacy found an issue: [Line should be 120 characters or less: currently 149 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +
Codacy found an issue: [Lines should not have trailing whitespace.](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  --size: calc( 90vw / 3 );
Codacy found an issue: [Unexpected whitespace after "(" in a single-line function (function-parentheses-space-inside)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 121 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Codacy found an issue: [Line should be 120 characters or less: currently 143 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
Codacy found an issue: [Line should be 120 characters or less: currently 137 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
Codacy found an issue: [Line should be 120 characters or less: currently 155 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  margin: calc( var( --ion-padding, 9px ) / 3 );
Codacy found an issue: [Unexpected whitespace after "(" in a single-line function (function-parentheses-space-inside)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 06:28 UTC, bafu commented on ios/App/App/AppDelegate.swift
> +    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is te
Codacy found an issue: [Line should be 120 characters or less: currently 214 characters](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 08:10 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-21 08:11 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +  height: 60vw;
Codacy found an issue: [Expected empty line before declaration (declaration-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 08:11 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +
Codacy found an issue: [Expected no more than 1 empty line (max-empty-lines)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 08:11 UTC, bafu commented on src/app/pages/storage/storage.page.scss
> +}
Codacy found an issue: [Unexpected empty line before closing brace (block-closing-brace-empty-line-before)](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019)

2020-09-21 17:23 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/app/pages/storage/storage.page.ts  8
+ src/app/utils/rx-operators.ts  33
         

Coverage decreased per file
===========================
- src/app/services/collector/signature/default-provider/default-provider.ts  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-23 06:59 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/app/pages/storage/storage.page.ts  16
+ src/app/utils/rx-operators.ts  33
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-23 07:07 UTC, shc261392 requested changes

2020-09-23 07:07 UTC, shc261392 commented on src/app/pages/storage/storage.page.html
> +          <div class="date-card-title"> <strong>All {{getDays( proofWithRaw.proof.timestamp)}}</strong> </div>
現在沒有 getDays 了
這段應該要跟前面一個 slide 一樣用 `proofsWithRawByDate$` 以及用一樣方式取得 date

2020-09-23 07:07 UTC, shc261392 commented on src/app/pages/storage/storage.page.ts
> +    // slidesPerView: 1,
要刪除

2020-09-23 07:18 UTC, bafu commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/app/utils/rx-operators.ts  33
+ src/app/pages/storage/storage.page.ts  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6209019&bid=20249313)

2020-09-23 07:25 UTC, shc261392 approved these changes

2020-09-23 07:25 UTC, merged