feat(dia-backend-wallet.service.ts): show custody wallet balance
numbersprotocol/capture-lite pull request #1269
Opened 2022-02-14 04:39 UTC by ruizehung

Update the api request url endpoint in `getManagedWallet$` to show NUM balance from custody/managed wallet instead of Capture wallet.

## Test Plan
![image](https://user-images.githubusercontent.com/35753861/153800938-4e929660-e373-4ef0-bb2e-ee34acd4d2f1.png)

2022-02-14 04:51 UTC, shc261392 requested changes
We have an endpoint named `/wallets/managed-wallet/`. To avoid ambiguity, the function name `getManagedWallet$` should be changed to `getNumWallet$` after confirming `getManagedWallet$` is not used in any other places.

2022-02-14 07:51 UTC, ruizehung commented
> We have an endpoint named `/wallets/managed-wallet/`. To avoid ambiguity, the function name `getManagedWallet$` should be changed to `getNumWallet$` after confirming `getManagedWallet$` is not used in any other places.

I think it's better for the function to be descriptive about what it does and abstract away the underlying details like which api endpoint it is calling. 

Is the `/wallets/num-wallet/` endpoint a temporary solution? Are we going to keep calling `/wallets/num-wallet/` in the future (and will not call `/wallets/managed-wallet/` anymore)? Or after the backend migration completes, we are going to swtich back to calling `/wallets/managed-wallet/`?

If we will keep calling `/wallets/num-wallet/` in the future, I think it makes sense to rename `getManagedWallet$` to  `getNumWallet$` and intrepret it as a function that gets the wallet used for NUM payment, which can be either asset wallet or managed wallet depending on how the backend is configured. Otherwise, I think it's better to keep its name as `getManagedWallet$`.

What do you think?

2022-02-15 06:19 UTC, shc261392 commented
> > We have an endpoint named `/wallets/managed-wallet/`. To avoid ambiguity, the function name `getManagedWallet$` should be changed to `getNumWallet$` after confirming `getManagedWallet$` is not used in any other places.
> 
> I think it's better for the function to be descriptive about what it does and abstract away the underlying details like which api endpoint it is calling.
> 
> Is the `/wallets/num-wallet/` endpoint a temporary solution? Are we going to keep calling `/wallets/num-wallet/` in the future (and will not call `/wallets/managed-wallet/` anymore)? Or after the backend migration completes, we are going to swtich back to calling `/wallets/managed-wallet/`?
> 
> If we will keep calling `/wallets/num-wallet/` in the future, I think it makes sense to rename `getManagedWallet$` to `getNumWallet$` and intrepret it as a function that gets the wallet used for NUM payment, which can be either asset wallet or managed wallet depending on how the backend is configured. Otherwise, I think it's better to keep its name as `getManagedWallet$`.
> 
> What do you think?

The endpoint will last until we decided to revise the wallet endpoints and make breaking changes in the future, and we don't have plan to do it yet. In short term, the likeness of deprecating `/wallets/num-wallet/` is lower than the likeness to deprecate/rename `/wallets/managed-wallet/`.

2022-02-15 07:36 UTC, shc261392 approved these changes

2022-02-15 07:37 UTC, merged