Feature update text from transaction history to asset wallet history
numbersprotocol/capture-lite pull request #1503
Opened 2022-04-04 11:00 UTC by sultanmyrza

for https://app.asana.com/0/0/1202066761864101/f

2022-04-06 05:09 UTC, shc261392 requested changes

2022-04-06 05:09 UTC, shc261392 commented on src/assets/i18n/zh-tw.json
> +    "assetWalletHistory": "資產錢包歷史",
As mentioned in the Asana task comment, use `資產交易紀錄` instead

```
[Tammy Yang](https://app.asana.com/0/1200886957195267/list)Today at 04:10
[sultanmyrza@gmail.com](https://app.asana.com/0/1201814667801575/list) please use "資產交易紀錄"
```

2022-04-06 05:48 UTC, sultanmyrza commented on src/assets/i18n/zh-tw.json
> +    "assetWalletHistory": "資產錢包歷史",
@shc261392 done

2022-04-08 07:58 UTC, shc261392 approved these changes
Looks good to me

2022-04-08 07:58 UTC, merged