Feat upgrade capacitor from 3 to 4 try 1
numbersprotocol/capture-lite pull request #2329
Opened 2022-11-18 13:06 UTC by sultanmyrza

2022-11-20 08:15 UTC, bafu requested changes

2022-11-20 08:15 UTC, bafu commented on src/app/shared/capacitor-plugins/mock-app-plugin.ts
> +  // addListener(
@sultanmyrza Suggest adding a comment about why commenting out and keep these codes so that we can catch up on the reason in the future quickly.

2022-11-23 09:12 UTC, sultanmyrza commented on src/app/shared/capacitor-plugins/mock-app-plugin.ts
> -  // addListener(
In the previous commit, I forgot to remove this commented code. It's safe to remove these lines.

2022-11-29 08:15 UTC, bafu approved these changes

2022-11-29 08:16 UTC, merged