Feature transaction detail & Fix "In Progress" activity
numbersprotocol/capture-lite pull request #286
Opened 2020-12-03 16:36 UTC by CS6

Feature transaction detail #220 
fix Can show different icon to distinguish different "In Progress" activity #199

2020-12-03 17:00 UTC, seanwu1105 commented
@CS6 ,`npm run lint && mom run test-ci` locally to avoid creating blocking PR. Also, you can create a draft PR before fixing the linting and testing errors.

2020-12-04 16:14 UTC, seanwu1105 requested changes

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.html
> +        <mat-label>From : {{ details.sender }}</mat-label>
Missing translation.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.html
> +        <mat-label>To : {{ details.receiver_email }}</mat-label>
Missing translation.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.html
> +  <ng-container>
Unnecessary `ng-container`.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.html
> +        <button [class]="details.status" mat-stroked-button disableRipple>
Currently, the type of `details` does not contain `status` property. Please extend the type of `details` from `Transaction`.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.ts
> +    private readonly router: Router,
Unused variable.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.ts
> +  details!: Transaction;
Incorrect type for the template use.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.ts
> +        this.details = details;
Set `this.details` directly in its declaration by using `Observable`. For example,

```typescript
details$ = this.route.paramMap.pipe(
  map(() => history.state)
)
```

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.ts
> +  InSendProgress = 'inSendProgress',
Ambiguous naming: `InSendProgress`.

2020-12-04 16:14 UTC, seanwu1105 commented on src/assets/i18n/en-us.json
> +  "inSendProgress": "In Progress",
From users' aspect, there's no way to tell the difference between `inSendProgress` and `inProgress` status from the same text, which makes this change fails to fix issue #199.

2020-12-04 16:14 UTC, seanwu1105 commented on src/assets/i18n/en-us.json
> +  "TransactionDetails": "活動資訊"
Rename and sort this property for consistency.

2020-12-04 16:14 UTC, seanwu1105 commented on src/assets/i18n/zh-tw.json
> +  "inSendProgress": "等待中",
From users' aspect, there's no way to tell the difference between `inSendProgress` and `inProgress` status from the same text, which makes this change fails to fix issue #199.

2020-12-04 16:14 UTC, seanwu1105 commented on src/assets/i18n/zh-tw.json
> +  "TransactionDetails": "活動資訊"
Rename and sort this property for consistency.

2020-12-04 16:14 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.ts
> +enum Status {
Avoid code duplication. Import `Status` enumeration from `activity.page.ts` instead.

2020-12-07 17:16 UTC, seanwu1105 requested changes
Please update the branch to `develop` before requesting review.

2020-12-07 17:54 UTC, CS6 commented
@seanwu1105  我沒有很懂，你是重構了嗎？我發現我好像都要重寫

2020-12-08 03:39 UTC, seanwu1105 requested changes

2020-12-08 03:39 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.html
> +        [class]="(details$ | async)?.status.__zone_symbol__value"
Do not use private properties from Angular, such as `__zone_symbol__value`. You should get the data asynchronously or resolve it first as `status` is a `Promise`.

2020-12-08 03:39 UTC, seanwu1105 commented on src/app/pages/home/activity/transaction-details/transaction-details.page.html
> +        {{ (details$ | async)?.status.__zone_symbol__value }}
Do not use private properties from Angular, such as `__zone_symbol__value`. You should get the data asynchronously or resolve it first as `status` is a `Promise`.

Also, translate it.

2020-12-08 06:20 UTC, seanwu1105 approved these changes

2020-12-08 06:22 UTC, merged