beta7.2 fix-2
numbersprotocol/capture-lite pull request #320
Opened 2020-12-09 08:40 UTC by CS6

Waiting to be Accepted 改回 In Progress
Replace  Button ViewAll => more information
Replace Title previewPostCapture => Preview
fix layout bug （fix timestamp 與後面時間切割成兩行）
fix title padding （fix 留白不夠）

參考
https://docs.google.com/presentation/d/1lnXs-dMzKT7IiAce4GdE9KLxohg2SFAWdlb-x0yaxtE/edit#slide=id.ga803bd26e4_0_8

2020-12-09 09:42 UTC, seanwu1105 requested changes

2020-12-09 09:42 UTC, seanwu1105 commented on src/assets/i18n/en-us.json
> +  "viewAll": "open more...",
Move the property to `"message.viewAll"` for consistency. The properties in root is for title which is capitalized to its key.

2020-12-09 09:42 UTC, seanwu1105 commented on src/assets/i18n/en-us.json
> +  "previewPostCapture": "Preview",
Remove the property `"preview"`. The properties in root is for title which is capitalized to its key.

2020-12-09 09:42 UTC, seanwu1105 commented on src/assets/i18n/en-us.json
> +  "waitingToBeAccepted": "In Progress",
Remove the property `"waitingToBeAccepted"`. The properties in root is for title which is capitalized to its key.

2020-12-09 09:42 UTC, seanwu1105 commented on src/assets/i18n/zh-tw.json
> +  "previewPostCapture": "預覽",
Remove the duplicated property.

2020-12-09 09:42 UTC, seanwu1105 commented on src/assets/i18n/zh-tw.json
> +  "waitingToBeAccepted": "等待中",
Change the property according to the suggestion of its English translation.

2020-12-09 09:42 UTC, seanwu1105 commented on src/assets/i18n/zh-tw.json
>    "viewAll": "檢視全部",
Change the property according to the suggestion of its English translation.

2020-12-09 12:43 UTC, seanwu1105 commented
@CS6 Please change the target branch to master as this is a patch to the latest release.

2020-12-09 16:04 UTC, seanwu1105 commented
@CS6 Please also rebase this fix to master branch and drop the commits between the latest develop HEAD and master HEAD as we don't want to release the fix with _Update dependencies. `63e45d6f`_, _Handle geolocation plugin errors and unknown location display (#308) `fe7cbdf6`_ and _Show contact list on contact selection dialog. #307 `fa8ef50`_.

2020-12-09 16:05 UTC, seanwu1105 requested changes
@CS6 Please also rebase this fix to master branch and drop the commits between the latest develop HEAD and master HEAD as we don't want to release the fix with _Update dependencies. `63e45d6f`_, _Handle geolocation plugin errors and unknown location display (#308) `fe7cbdf6`_ and _Show contact list on contact selection dialog. #307 `fa8ef50`_.

2020-12-09 16:33 UTC, seanwu1105 commented
@CS6 Did you drop the three commits I mentioned after rebasing on master? I still see the commits :thinking:

2020-12-09 16:37 UTC, CS6 commented
@seanwu1105  我這邊看是 rebase 到 master [0.10.0]( c5971d,983a1a)，應該有符合需求？

2020-12-09 16:42 UTC, seanwu1105 commented
@CS6 rebase 以外，在 master 到 develop 之間有三個 commits 需要被 dropped 避免這個 patch 有新的 features 在裡面。

一開始的 patch 應該是要從 master checkout 就不用像這次還要 rebase 和 drop commits。

2020-12-10 02:26 UTC, seanwu1105 commented
@CS6 After the discussion on Slack, you do not need to drop the commits. All you need to do is change back the target branch to develop, and then I will merge this fix to the next release (beta 7.3). Thanks.

> Sean Wu  9:56 AM
> @Scott Yan 目前還在等 pr 收起來 https://github.com/numbersprotocol/capture-lite/pull/320
> 不過因為今天要 release 7.3，不知道能不能夠一併釋出就好？（cc @Tammy）
> 
> Tammy  9:57 AM
> @Sean Wu 我原則上希望 UI release 跟 功能 release 分開，因為兩者 QA 要測試的重點不同。不過如果合併比較節省 efforts，可以合併

2020-12-10 03:11 UTC, seanwu1105 approved these changes

2020-12-10 03:30 UTC, merged