Feature use server side notification for push
numbersprotocol/capture-lite pull request #373
Opened 2020-12-16 07:14 UTC by shc261392

- Update language settings to DIA backend.

- Replace local notification for push notification data with built-in notification of push notification.

- Workaround: Force change detection when the inbox emits value to update the badge when returning to the App foreground by clicking the notification in background.

2020-12-16 08:26 UTC, seanwu1105 requested changes
I have tested on Android Exodus 1s. However, I cannot receive any push notification whenever the app is on foreground or background.

2020-12-16 08:26 UTC, seanwu1105 commented on src/app/services/dia-backend/auth/dia-backend-auth.service.ts
> +            language,
This line can have a better format.

2020-12-16 14:39 UTC, shc261392 commented
The updated code could work for both iOS and Android, foreground and background. Tested on iPhone 7 Plus (iOS 13.6) and Nokia 6.1 (Android 10).

Known issue: the notification icon of Android when receiving the notification in background is incorrect (white block icon).

2020-12-17 02:58 UTC, seanwu1105 approved these changes

2020-12-17 03:00 UTC, merged