Fix PostCaptures Accidentally Displayed on Capture tab.
numbersprotocol/capture-lite pull request #431
Opened 2020-12-30 16:34 UTC by seanwu1105

Fix #379 and #383 by removing pre-fetching `Proof`s and disk cache of `DiaBackendAsset`s.

Previously, the app will assume ALL Captures and PostCaptures are stored (in the form of `Proof`) in local, and thus require pre-feching `Proof`s. With this fix, the app will first fetch the data from the backend then the local `Proof`s. By doing this, the issues #379 and #383 should be fixed as there would be no permanent local cache of `DiaBackendAsset`s. Everything would stay synced to the backend.

The implementation is a little bit messy regarding the part joining `DiaBackendAsset`s and `Proof`s. A better implementation could be found in [this experimental repo](https://github.com/numbersprotocol/capture-lite-performance/blob/develop/src/app/features/home/capture/capture-item/capture-item.component.ts#L35), which provides an uniform interface for `DiaBackendAsset`, `Proof` and `Assets`. However, the "better" implementation is still unstable. The messy implementation will be refactored in the future.

2020-12-31 07:56 UTC, shc261392 requested changes

2020-12-31 07:56 UTC, shc261392 commented on src/app/pages/home/home.page.ts
>      return combineLatest([
I've found that this observable will not emit value if following the steps:

1. On browser, clean all previous data
2. Login with a clean account
3. Disable network and take 1 capture
4. Even if reload the page, it still won't emit

I did a bit of console log tracking and finds something weird. It's the `proofRepository.getAll$()` that didn't emit value. It seems in capacitor-filesystem-table, the `initialize()` never returns.

2020-12-31 07:56 UTC, shc261392 commented on src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
> +  private readonly fetchAllCache$ = new BehaviorSubject<DiaBackendAsset[]>([]);
By using a in-memory cache, does that mean it's not possible to determine if an asset has been uploaded or not if the user is offline?

For example, will the user see the `!` mark on all previous captures when trying to use Capture offline?

2020-12-31 07:56 UTC, shc261392 commented on src/app/pages/home/home.page.ts
>      return combineLatest([
It seems this won't happen if I enable the network again. And if I disable the network, the problem reappears.

2021-01-04 02:33 UTC, seanwu1105 commented on src/app/pages/home/asset/asset.page.ts
> +      const latitude = asset.information.information.find(
@shc261392 The [documentation](https://dia-backend-dev.numbersprotocol.io/redoc/#operation/api_v2_assets_read) indicates `meta` is __required__. Where can I find this piece of information?

2021-01-05 02:50 UTC, shc261392 approved these changes

2021-01-05 02:57 UTC, merged